name: Kanban management
on:
  pull_request_target:
    types: [opened, reopened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.KANBAN_TOKEN }}

jobs:
  assign_one_project:
    name: Add new pull requests to the kanban
    runs-on: ubuntu-latest
    steps:
    - name: Assign new pull requests to the project board
      uses: actions/add-to-project@v0.5.0
      with:
        project-url: https://github.com/orgs/rockandror/projects/1
        github-token: ${{ secrets.KANBAN_TOKEN }}
